// POST http://localhost:8080/api/portfolios/addStock/PORTFOLIOID/TICKER/AMOUNT HTTP/1.1
// content-type: application/json


POST http://localhost:8080/api/portfolios/addStock/5f5ecf766bf9793a7412d8f1/AAPL/100 HTTP/1.1
content-type: application/json
