POST http://localhost:8080/api/trades/addTrade/5f5ecf766bf9793a7412d8f1 HTTP/1.1
content-type: application/json

{
    "stockTicker": "AMZN",
    "quantity": 3,
    "requestPrice": 3132.58,
    "tStatus": "CREATED"
}

