POST http://localhost:8080/api/trades/addTrade/5f623103c7e8ad1aca356733 HTTP/1.1
content-type: application/json

{
    "stockTicker": "TSLA",
    "quantity": 3,
    "requestPrice": 3132.58,
    "tStatus": "CREATED"
}

